# Generated by Django 5.1.7 on 2025-04-24 21:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_id'),  # Depends on the safe null+backfill migration
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(
                max_length=32,
                unique=True,
                default=users.models.generate_user_id,
                editable=False,
            ),
        ),
    ]
