# Generated by Django 5.1.7 on 2025-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='energy_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='prep_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
