# Generated by Django 5.1.7 on 2025-06-04 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_remove_recipe_instructions_ingredient_calories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUSDAFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdcId', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50)),
                ('publication_date', models.DateField(null=True)),
                ('raw_data', models.JSONField()),
                ('calories', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('carbs', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('fetch_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('planned_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('total_calories', models.FloatField(null=True)),
                ('total_protein', models.FloatField(null=True)),
                ('total_carbs', models.FloatField(null=True)),
                ('total_fat', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('planned_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.plannedmeal')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.storedusdafood')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='foods',
            field=models.ManyToManyField(through='diet.PlannedMealFood', to='diet.storedusdafood'),
        ),
        migrations.CreateModel(
            name='UserFoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('use_count', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.storedusdafood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='plannedmeal',
            index=models.Index(fields=['user', 'planned_date'], name='diet_planne_user_id_9fdd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedmeal',
            index=models.Index(fields=['user', 'meal_type'], name='diet_planne_user_id_80634d_idx'),
        ),
        migrations.AddIndex(
            model_name='userfoodhistory',
            index=models.Index(fields=['user', '-last_used'], name='diet_userfo_user_id_b876b6_idx'),
        ),
        migrations.AddIndex(
            model_name='userfoodhistory',
            index=models.Index(fields=['user', '-use_count'], name='diet_userfo_user_id_b0a8a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfoodhistory',
            unique_together={('user', 'food')},
        ),
    ]
