# Generated by Django 5.1.7 on 2025-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_storedusdafood_plannedmeal_plannedmealfood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdietarypreferences',
            name='meal_baseline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdietarypreferences',
            name='meal_planning_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
