# Generated by Django 5.1.7 on 2025-06-11 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_userdietarypreferences_meal_baseline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealdb_id', models.CharField(max_length=20)),
                ('meal_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('meal_thumb', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('source_link', models.URLField(blank=True)),
                ('raw_mealdb_data', models.JSONField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('preferred_meal_type', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-saved_at'], name='diet_usersa_user_id_4a265e_idx'), models.Index(fields=['user', 'favorite'], name='diet_usersa_user_id_b18b02_idx')],
                'unique_together': {('user', 'mealdb_id')},
            },
        ),
    ]
