# Generated by Django 5.1.7 on 2025-06-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_usersavedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='plan_json',
            field=models.JSONField(blank=True, help_text='Cached JSON representation of the meal plan for AI prompting and quick access', null=True),
        ),
    ]
