# Generated by Django 5.1.7 on 2025-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_plannedmeal_plan_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedmeal',
            name='macros_json',
            field=models.JSONField(blank=True, help_text='AI-generated nutrition data (calories, protein, etc.)', null=True),
        ),
    ]
