# Generated by Django 5.1.7 on 2025-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_usersavedmeal_macros_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedmeal',
            name='recommended_servings',
            field=models.IntegerField(blank=True, help_text='Recommended number of servings for this recipe', null=True),
        ),
    ]
