# Generated by Django 5.1.7 on 2025-06-14 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_usersavedmeal_recommended_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedmeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersavedmeal',
            name='macros_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
