# Generated by Django 5.1.7 on 2025-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_usersavedmeal_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealdb_id', models.CharField(max_length=20, unique=True)),
                ('meal_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('meal_thumb', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('source_link', models.URLField(blank=True)),
                ('raw_mealdb_data', models.JSONField()),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
                ('search_tags', models.JSONField(default=list, help_text='Tags for quick filtering')),
                ('ingredients_text', models.TextField(blank=True, help_text='Concatenated ingredients for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='diet_bulkre_categor_996b6c_idx'), models.Index(fields=['area'], name='diet_bulkre_area_99606d_idx'), models.Index(fields=['created_at'], name='diet_bulkre_created_3ecc0f_idx')],
            },
        ),
    ]
