# Generated by Django 5.1.7 on 2025-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_bulkrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkrecipe',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkrecipe',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
