# Generated by Django 5.1.7 on 2025-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_alter_bulkrecipe_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedmeal',
            name='source',
            field=models.CharField(default='mealdb_api', help_text="Source of the meal (e.g., 'mealdb_api', 'rag')", max_length=20),
        ),
    ]
