# Generated by Django 5.1.7 on 2025-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_usersavedmeal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedmeal',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersavedmeal',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
