# Generated by Django 5.1.7 on 2025-06-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0015_plannedmeal_saved_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedmeal',
            name='saved_meal',
        ),
    ]
