# Generated by Django 5.1.7 on 2025-06-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_remove_plannedmeal_saved_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='saved_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.usersavedmeal'),
        ),
    ]
