# Generated by Django 5.1.7 on 2025-06-22 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0017_plannedmeal_saved_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedmeal',
            name='saved_meal',
        ),
        migrations.CreateModel(
            name='MealPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_action', models.CharField(default='manual', max_length=50)),
                ('meal_plan_snapshot', models.JSONField()),
                ('daily_totals_snapshot', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='diet_mealpl_user_id_221571_idx')],
            },
        ),
    ]
