# Generated by Django 5.1.7 on 2025-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0018_remove_plannedmeal_saved_meal_mealplanversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitraryIngredientForRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArbitraryRecipeForRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('ingredients_json', models.JSONField()),
                ('instructions', models.TextField()),
                ('source_id', models.CharField(help_text='Original ID from BulkRecipe', max_length=50)),
                ('is_herring_version', models.BooleanField(default=False)),
            ],
        ),
    ]
