# Generated by Django 5.1.7 on 2025-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_arbitraryingredientforrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedmeal',
            name='prep_time_min',
            field=models.FloatField(blank=True, help_text='Estimated preparation time in minutes (AI-generated)', null=True),
        ),
    ]
