# Generated by Django 5.1.7 on 2025-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_wellnessscorehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='lifestyle',
            field=models.TextField(blank=True),
        ),
    ]
