# Generated by Django 5.1.7 on 2025-05-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_healthinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('weekly_activity_target', models.IntegerField(blank=True, null=True)),
                ('goal_description', models.TextField(blank=True)),
                ('ai_weekly_plan', models.TextField(blank=True, null=True)),
                ('ai_monthly_plan', models.TextField(blank=True, null=True)),
                ('ai_priority', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
