# Generated by Django 5.1.7 on 2025-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_goalplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsight',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
