# Generated by Django 5.1.7 on 2025-05-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_healthinsight_last_profile_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsight',
            name='last_profile_update',
        ),
        migrations.AddField(
            model_name='goalplan',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
