# Generated by Django 5.1.7 on 2025-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_healthinsight_last_profile_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalplan',
            name='ai_priority_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
