# Generated by Django 5.1.7 on 2025-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_goalplan_ai_priority_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalplan',
            name='ai_target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
